### ISSUE TITLE
Alternative official timetable data source

### ISSUE THREAD

**Issue by hongshaoyang** [nusmodifications/nusmods#346]
hi, kind admins. I'm just a noob lurking around so feel free to ignore this issue if it has been considered.

> NUSMods obtains timetable data automatically from CORS and IVLE.

It is currently Sem 1 Week 13 as I write and CORS still does not show Sem 2 timetable info. However [the official NUS builder](https://webrb.nus.edu.sg/ctt/builder.aspx) has that info already (not for all mods, of course, as release of information depends on individual NUS depts).

Possible to scrape this source for module information? Ambitious, but I hope it's worth the try.

**Comment by yangshun** [comment]
We're working on fixing it in https://github.com/nusmodifications/nusmods-api

**Comment by yangshun** [comment]
The official timetable builder does not display module data on webpages and also the effort required to write a new scraper will be immense. I'm afraid scraping it will be near impossible

**Comment by yangshun** [comment]
Fixed thanks to @li-kai and @ngzhian

**Comment by ravic1995** [comment]
Correct me if I am wrong, but I think this issue is still persistent. 
Even now I am unable to build my timetable for the 2nd semester
I am not sure if everyone is facing the same issue.

**Comment by li-kai** [comment]
@ravic1995 Hi ravic, we truly only depend on [cors](https://myaces.nus.edu.sg/cors/jsp/report/ModuleInfoListing.jsp) as a data source. It currently does not show sem 2 data, and we're unable to get data as a result. We'll explore capabilities to obtain information earlier in the future.

**Comment by ravic1995** [comment]
@li-kai Ohkk i see, no worries.
